### ISSUE TITLE
Skip colon when an empty type is specified and writing a google docstring

### ISSUE THREAD

**Issue by AWhetter** [cbillingham/docconvert#6]
Reading the following docstring

```
"""
Description

:return: A thing
:rtype: C{}
"""
```

results in the following Google docstring

```
"""Description

Returns:
     : A thing
"""
```

I would expect the colon to be skipped in the output because the type is empty.

**Comment by cbillingham** [comment]
Same situation for this one.
I get this output with the current version:
```
"""Description

Returns:
    C{}: A thing
"""
```

**Comment by AWhetter** [comment]
I can't reproduce this one again either. I'm not sure why it failed the first time.
