### ISSUE TITLE
Support for async definitions

### ISSUE THREAD

**Issue by Peter9192** [cbillingham/docconvert#8]
Thanks for writing this tool! I tried using it on a project in which we have several `async def`s, and found that those dostrings seem to be ignored. Is this expected, or is there a way to make it work for async code as well?

**Comment by cbillingham** [comment]
Oh yeah. We're probably just missing handling that in the AST parsing part. Let me see how complex it would be to add it in and I'll get back to you. Thanks for opening an issue!

**Comment by cbillingham** [comment]
Yep looks like we were just missing parsing for async function defs. I went ahead and added support for that. Will push up a new version when that is merged

**Comment by cbillingham** [comment]
Released in v2.1.0. Thanks for reporting the issue
